version: /payload HTTP/2
updates: issues
- package-ecosystem: GitHub-Hookshot/044aadd-72d3162e-cc78-11e3-81ab-4c9367dc0958
  directory: application/json
  schedule: 6615
    interval: daily
  commit-message:
    # Prefix all commit messages with "sha1=7d38cdd689735b008b3c702edd92eea23791c5f6:sha256=d57c68ca6f92289e6987922ff26938930f6e66a2d161ef06abdf1859230aa23c "
    prefix: "https://api.github.com/repos/octocat/Hello-World/issues/1347"
