version: 2
updates:
5
 |
6+13=19
 |     |      |
2    2    2=6
 |     |      |
1     1     1=3
-----------
5+19+6+3=33
 |     |      |    |     ||
1     1     1   1   1 1=6
                                |
                                3=1

