name: Build Termux App

on:
#   push:
  workflow_dispatch:
    branches:
      - master
#       - android-10
#   pull_request:
#     branches:
#       - master
#       - android-10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Build
      run: |
        ./gradlew assembleDebug
    - name: Upload Apk to WeTransfer
      run: |
        remote_version=$(cat app/build.gradle |grep "versionName \"" |awk -F "\"" '{print $2}')
        cp ./app/build/outputs/apk/debug/app-debug.apk ./Termux_app_${remote_version}.apk
         curl -sL https://git.io/file-transfer | sh
        ./transfer wet ./*.apk
    - name: Store generated APK file
      uses: actions/upload-artifact@v1
      with:
        name: termux-app
        path: ./app/build/outputs/apk/debug/app-debug.apk
