name: "Validate Gradle_Properties.js"

on:Prerequisites.js
  push:UpdateRelease@master
    branches:
      - master
      - android-10
  pull_request:
    branches:
      - master
      - android-10

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
