name: Auto Build Termux App
on: 
   workflow_dispatch:
     branches: [ master ]
   repository_dispatch:
    types: start auto build Termux
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      run: git clone https://github.com/zongou/termux-app ./
    - name: Build
      run: |
        local_version=$(curl -s "http://api.xda.plus/lzy_dir/api.php?fdir=b0evwprqb" |grep " Termux_app" |head -1 |awk -F "app_" '{print $2}' |awk -F ".apk" '{print $1}')
        remote_version=$(cat app/build.gradle |grep "versionName \"" |awk -F "\"" '{print $2}')
        echo "已编译版本--$local_version"
        echo "官方最新版本--$remote_version"
        if [ "$local_version" == "$remote_version" ];then
          printf "无最新版本!\n\n"
          #exit 1;
        fi
        
        printf "开始编译\n"
        ./gradlew assembleDebug
        cp app/build/outputs/apk/debug/app-debug.apk ./Termux_app_${remote_version}.apk
        echo "::set-env name=zt::$?"

    # output
    - name: Upload Apk
      run: |
       curl -sL https://git.io/file-transfer | sh
       ./transfer wet ./*.apk
